from __future__ import annotations
from pathlib import Path
from typing import Any
import json
from ..models import write_json


TRANSITION_FILTERS = {
    "cut": None,
    "fade in": "fade=t=in:d={dur}",
    "fade out": "fade=t=out:d={dur}:start_time={start}",
    "dissolve": "dissolve",
    "wipe left": "wipe=1:0.3",
    "wipe right": "wipe=-1:0.3",
}


def export_ffmpeg(
    project: str | Path,
    shot_graph_path: str | Path | None = None,
    input_pattern: str = "shot_{index:03d}.mp4",
    output_name: str = "lookbook_assembly.mp4",
    fps: int = 24,
) -> dict[str, Any]:
    """Generate an FFmpeg assembly script from shot graph data.

    Creates a batch script that concatenates individual shot videos
    with transitions, producing a complete animation sequence.

    Args:
        project: lookBOOK project path
        shot_graph_path: Path to shot_graph.json (auto-detected)
        input_pattern: Pattern for input clip filenames ({index} = shot_index)
        output_name: Name of the final assembled video
        fps: Frames per second

    Returns:
        Dict with script paths and metadata.
    """
    project = Path(project)

    if shot_graph_path is None:
        shot_graph_path = project / "analysis" / "shot_graph.json"
    if not shot_graph_path.exists():
        raise FileNotFoundError(f"Shot graph not found at {shot_graph_path}.")

    shot_data = json.loads(shot_graph_path.read_text(encoding="utf-8"))
    shots = shot_data.get("shots", [])

    if not shots:
        raise ValueError("No shots found in shot graph.")

    export_dir = project / "exports" / "ffmpeg"
    export_dir.mkdir(parents=True, exist_ok=True)

    total_dur = shot_data.get("total_duration_seconds", sum(s["duration_seconds"] for s in shots))
    output_path = export_dir / output_name

    # Write input file list for concat demuxer
    concat_lines: list[str] = []
    temp_files: list[str] = []

    for i, shot in enumerate(shots):
        index = shot["shot_index"]
        input_file = input_pattern.format(index=index)
        dur = shot["duration_seconds"]
        transition = shot.get("transition_in", "cut")

        concat_lines.append(f"file '{input_file}'")
        concat_lines.append(f"duration {dur}")

        # For transitions, we need the concat filter graph
        trans_filter = TRANSITION_FILTERS.get(transition)
        if trans_filter and transition != "cut":
            temp_files.append(input_file)

    fallback_cmd_parts = []
    for i, shot in enumerate(shots):
        index = shot["shot_index"]
        input_file = input_pattern.format(index=index)
        fallback_cmd_parts.append(f"-i {input_file}")

    # Simple concat (no complex transitions — good default)
    concat_script = """@echo off
REM lookBOOK FFmpeg Assembly Script
REM Generated by lookbook export-ffmpeg
REM
REM Place generated shot videos in this directory matching:
REM   %s
REM Then run this script.
REM
REM Simple concat (no transitions):
ffmpeg -f concat -safe 0 -i file_list.txt -c copy "%s"
echo.
echo Assembly complete: %s
""" % (
        input_pattern.replace("{index:03d}", "000"),
        output_name,
        output_name,
    )

    # Write file list
    file_list_path = export_dir / "file_list.txt"
    file_list_path.write_text("\n".join(concat_lines), encoding="utf-8")

    # Write the batch script
    script_path = export_dir / "assemble.bat"
    script_path.write_text(concat_script, encoding="utf-8")

    # Also write a shell-compatible version
    sh_script = concat_script.replace("@echo off", "#!/bin/bash").replace("REM", "#")
    sh_script_path = export_dir / "assemble.sh"
    sh_script_path.write_text(sh_script, encoding="utf-8")

    export = {
        "schema": "lookbook.ffmpeg_assembly.v0.2",
        "total_shots": len(shots),
        "total_duration_seconds": total_dur,
        "fps": fps,
        "output_file": str(output_path.relative_to(project)),
        "assembly_script": str(script_path.relative_to(project)),
        "shell_script": str(sh_script_path.relative_to(project)),
        "file_list": str(file_list_path.relative_to(project)),
        "instructions": (
            f"1. Render each shot as {input_pattern.replace('{index:03d}', 'NNN')}.mp4\n"
            f"2. Place all video files alongside the assembly scripts in {export_dir}\n"
            f"3. Run assemble.bat (Windows) or assemble.sh (Linux/Mac)\n"
        ),
    }

    write_json(export_dir / "ffmpeg_assembly.json", export)

    return export
